version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    command: python3 manage.py runserver 0.0.0.0:8000
