# Generated by Django 5.1.5 on 2025-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
