# Generated by Django 5.1.5 on 2025-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_remove_cart_item_cart_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
